### ISSUE TITLE
npm i --save react react-dom react-sliding-pane - issue

### ISSUE THREAD

**Issue by erwinagpasa** [DimitryDushkin/sliding-pane#50]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: reactjs-testimonials@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-sliding-pane@6.1.2
npm ERR! node_modules/react-sliding-pane
npm ERR!   react-sliding-pane@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/erwinagpasa/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erwinagpasa/.npm/_logs/2020-12-26T19_15_28_083Z-debug.log
➜  reactjs-testimonials git:(main) npm i --save react react-dom react-sliding-pane
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: reactjs-testimonials@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-sliding-pane@6.1.2
npm ERR! node_modules/react-sliding-pane
npm ERR!   react-sliding-pane@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/erwinagpasa/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erwinagpasa/.npm/_logs/2020-12-26T19_18_46_123Z-debug.log

**Comment by DimitryDushkin** [comment]
Hey! Looks like peerDeps should be modified to support react 17. I'll fix it.

**Comment by DimitryDushkin** [comment]
Checkout v 7.0. Should be fixed. Report if it is not. Thanks!

**Comment by erwinagpasa** [comment]
> Hey! Looks like peerDeps should be modified to support react 17. I'll fix it.

Thanks bro

**Comment by yashcr07** [comment]
> Checkout v 7.0. Should be fixed. Report if it is not. Thanks!

Hi Dimitry, I think you missed updating the releases, its says 6.0.0 as the latest version.

**Comment by DimitryDushkin** [comment]
> > Checkout v 7.0. Should be fixed. Report if it is not. Thanks!
> 
> Hi Dimitry, I think you missed updating the releases, its says 6.0.0 as the latest version.

Yeah, thanks.)
